# Generated by Django 6.0.6 on 2026-07-02 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces, dashes, and parentheses allowed).', regex='^\\+?[\\d\\s\\-\\(\\)]{10,17}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces, dashes, and parentheses allowed).', regex='^\\+?[\\d\\s\\-\\(\\)]{10,17}$')]),
        ),
    ]
